version: '3.1'

services:
  node:
    build:
      dockerfile: Dockerfile.dev
      context: .
      args:
        - NODE_ENV=development

    command: npm run start

    ports:
      - "8000:8000"
    volumes:
      - .:/opt/app
    environment:
      - NODE_ENV=development

    labels:
      - "traefik.port=8000"
      - "traefik.backend=service_1"
      - "traefik.protocol=http"
      - "traefik.frontend.entryPoints=http"
      - "traefik.frontend.rule=Host:service_1.docker.localhost"


  traefik:
    image: traefik:v1.0.1
    command: --web --docker --docker.watch --docker.domain=docker.localhost --logLevel=DEBUG --entryPoints="Name:http Address::80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/etc/traefik/traefik.toml
